### ISSUE TITLE
Fix package deprecation warnings

### ISSUE THREAD

**Issue by BrandonOCasey** [videojs/generator-videojs-plugin#272]
* [ ] `circular-json` ->
  * [ ] `flat-entry-cache` -> `eslint` -> `videojs-standard`: see https://github.com/eslint/eslint/issues/11257
  * [ ] `log4js` -> `karma`: see https://github.com/log4js-node/log4js-node/issues/789
* [ ] `tsml` -> `video.js`: see https://github.com/videojs/video.js/pull/5649
* [ ] `fs-promise` -> `karma-safaritechpreview-launcher`: see https://github.com/marcoscaceres/karma-safaritechpreview-launcher/issues/8
* [ ] `text-encoding` -> `sinon`: fixed in v7
* [ ] `nomnom` -> `jsonlint` -> `eslint-plugin-json-light` -> `videojs-standard`: see https://github.com/zaach/jsonlint/pull/117
* [ ] `turbocolor` -> `postcss-progress` -> `videojs-generate-postcss-config`: fixed in v1.1.1

**Comment by LoneRifle** [comment]
log4js-node/log4js-node#789 has now been merged
